//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_ARTWORK_REQUEST_SALES_ORDER_REPEAT
    {
        public int ARTWORK_SALES_ORDER_REPEAT_ID { get; set; }
        public int ARTWORK_REQUEST_ID { get; set; }
        public string SALES_ORDER_NO { get; set; }
        public string SALES_ORDER_ITEM { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string COMPONENT_ITEM { get; set; }
        public string COMPONENT_MATERIAL { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
       public string RECHECK_ARTWORK { get; set; }
    }
}
