//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_ARTWORK_PROCESS_PA
    {
        public int ARTWORK_SUB_PA_ID { get; set; }
        public int ARTWORK_SUB_ID { get; set; }
        public Nullable<int> PA_USER_ID { get; set; }
        public Nullable<int> PG_USER_ID { get; set; }
        public Nullable<int> MATERIAL_GROUP_ID { get; set; }
        public string MATERIAL_NO { get; set; }
        public Nullable<int> RD_REFERENCE_NO_ID { get; set; }
        public Nullable<int> PRODUCT_CODE_ID { get; set; }
        public Nullable<int> TYPE_OF_ID { get; set; }
        public string TYPE_OF_OTHER { get; set; }
        public Nullable<int> PRIMARY_SIZE_ID { get; set; }
        public string PRIMARY_SIZE_OTHER { get; set; }
        public Nullable<int> CONTAINER_TYPE_ID { get; set; }
        public string CONTAINER_TYPE_OTHER { get; set; }
        public Nullable<int> LID_TYPE_ID { get; set; }
        public string LID_TYPE_OTHER { get; set; }
        public Nullable<int> TYPE_OF_2_ID { get; set; }
        public string TYPE_OF_2_OTHER { get; set; }
        public Nullable<int> PACKING_STYLE_ID { get; set; }
        public string PACKING_STYLE_OTHER { get; set; }
        public Nullable<int> PACK_SIZE_ID { get; set; }
        public string PACK_SIZE_OTHER { get; set; }
        public Nullable<int> PLANT_REGISTERED_ID { get; set; }
        public string PLANT_REGISTERED_OTHER { get; set; }
        public Nullable<int> COMPANY_ADDRESS_ID { get; set; }
        public string COMPANY_ADDRESS_OTHER { get; set; }
        public Nullable<int> PRODICUTION_PLANT_ID { get; set; }
        public string PRODICUTION_PLANT_OTHER { get; set; }
        public Nullable<int> CATCHING_PERIOD_ID { get; set; }
        public string CATCHING_PERIOD_OTHER { get; set; }
        public Nullable<int> CATCHING_METHOD_ID { get; set; }
        public string CATCHING_METHOD_OTHER { get; set; }
        public Nullable<int> SCIENTIFIC_NAME_ID { get; set; }
        public string SCIENTIFIC_NAME_OTHER { get; set; }
        public Nullable<int> SPECIE_ID { get; set; }
        public string SPECIE_OTHER { get; set; }
        public Nullable<int> PMS_COLOUR_ID { get; set; }
        public string PMS_COLOUR_OTHER { get; set; }
        public Nullable<int> PROCESS_COLOUR_ID { get; set; }
        public string PROCESS_COLOUR_OTHER { get; set; }
        public Nullable<int> TOTAL_COLOUR_ID { get; set; }
        public string TOTAL_COLOUR_OTHER { get; set; }
        public Nullable<int> STYLE_OF_PRINTING_ID { get; set; }
        public string STYLE_OF_PRINTING_OTHER { get; set; }
        public Nullable<int> DIRECTION_OF_STICKER_ID { get; set; }
        public string DIRECTION_OF_STICKER_OTHER { get; set; }
        public Nullable<int> PRINTING_STYLE_OF_PRIMARY_ID { get; set; }
        public string PRINTING_STYLE_OF_PRIMARY_OTHER { get; set; }
        public string CUSTOMER_DESIGN { get; set; }
        public string CUSTOMER_DESIGN_OTHER { get; set; }
        public string CUSTOMER_SPEC { get; set; }
        public string CUSTOMER_SPEC_OTHER { get; set; }
        public string CUSTOMER_SIZE { get; set; }
        public string CUSTOMER_SIZE_OTHER { get; set; }
        public string CUSTOMER_NOMINATES_VENDOR { get; set; }
        public string CUSTOMER_NOMINATES_VENDOR_OTHER { get; set; }
        public string CUSTOMER_NOMINATES_COLOR { get; set; }
        public string CUSTOMER_NOMINATES_COLOR_OTHER { get; set; }
        public string CUSTOMER_BARCODE_SCANABLE { get; set; }
        public string CUSTOMER_BARCODE_SCANABLE_OTHER { get; set; }
        public string CUSTOMER_BARCODE_SPEC { get; set; }
        public string CUSTOMER_BARCODE_SPEC_OTHER { get; set; }
        public Nullable<int> PRINTING_STYLE_OF_SECONDARY_ID { get; set; }
        public string PRINTING_STYLE_OF_SECONDARY_OTHER { get; set; }
        public Nullable<int> FIRST_INFOGROUP_ID { get; set; }
        public string FIRST_INFOGROUP_OTHER { get; set; }
        public string PIC_MKT { get; set; }
        public string COMPLETE_INFOGROUP { get; set; }
        public string NOTE_OF_PA { get; set; }
        public string PACKAGE_QUANTITY { get; set; }
        public string WASTE_PERCENT { get; set; }
        public string COURIER_NO { get; set; }
        public string PRODUCTION_EXPIRY_DATE_SYSTEM { get; set; }
        public string SERIOUSNESS_OF_COLOR_PRINTING { get; set; }
        public string SHADE_LIMIT { get; set; }
        public string NUTRITION_ANALYSIS { get; set; }
        public Nullable<int> THREE_P_ID { get; set; }
        public Nullable<int> TWO_P_ID { get; set; }
        public string READY_CREATE_PO { get; set; }
        public string RECEIVE_SHADE_LIMIT { get; set; }
        public string REFERENCE_MATERIAL { get; set; }
        public string REQUEST_MATERIAL_STATUS { get; set; }
        public string CHANGE_POINT { get; set; }
        public string IS_LOCK_PRODUCT_CODE { get; set; }
        public string IS_RETRIEVE_BY_AW_REPEAT { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string MATERIAL_DESCRIPTION { get; set; }
        public string RUNNING { get; set; }
    }
}
