//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_ARTWORK_MATERIAL_LOCK_DETAIL
    {
        public int MATERIAL_LOCK_DETAIL_ID { get; set; }
        public int MATERIAL_LOCK_ID { get; set; }
        public string MATERIAL_NO { get; set; }
        public string SALES_ORDER_NO { get; set; }
        public string SOLD_TO { get; set; }
        public string SHIP_TO { get; set; }
        public string COUNTRY { get; set; }
        public string ZONE { get; set; }
        public string BRAND { get; set; }
        public string PRODUCT_CODE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
