//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_ARTWORK_MAPPING_PO
    {
        public int ARTWORK_MAPPING_PO_ID { get; set; }
        public string ARTWORK_NO { get; set; }
        public string PO_NO { get; set; }
        public string PO_ITEM { get; set; }
        public string SO_NO { get; set; }
        public string SO_ITEM { get; set; }
        public string MATERIAL_NO { get; set; }
        public string IS_ACTIVE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
