//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_ARTWORK_PROCESS_ASSIGN_SO_HEADER
    {
        public int ASSIGN_SO_HEADER_ID { get; set; }
        public int ARTWORK_PROCESS_SO_ID { get; set; }
        public int ARTWORK_REQUEST_ID { get; set; }
        public int ARTWORK_SUB_ID { get; set; }
        public string SALES_ORDER_NO { get; set; }
        public string SOLD_TO { get; set; }
        public string SOLD_TO_NAME { get; set; }
        public Nullable<decimal> LAST_SHIPMENT_DATE { get; set; }
        public Nullable<decimal> DATE_1_2 { get; set; }
        public Nullable<System.DateTime> CREATE_ON { get; set; }
        public Nullable<System.DateTime> RDD { get; set; }
        public string PAYMENT_TERM { get; set; }
        public string LC_NO { get; set; }
        public Nullable<decimal> EXPIRED_DATE { get; set; }
        public string SHIP_TO { get; set; }
        public string SHIP_TO_NAME { get; set; }
        public string SOLD_TO_PO { get; set; }
        public string SHIP_TO_PO { get; set; }
        public string SALES_GROUP { get; set; }
        public string MARKETING_CO { get; set; }
        public string MARKETING_CO_NAME { get; set; }
        public string MARKETING { get; set; }
        public string MARKETING_NAME { get; set; }
        public string MARKETING_ORDER_SAP { get; set; }
        public string MARKETING_ORDER_SAP_NAME { get; set; }
        public string SALES_ORG { get; set; }
        public string DISTRIBUTION_CHANNEL { get; set; }
        public string DIVITION { get; set; }
        public string SALES_ORDER_TYPE { get; set; }
        public string HEADER_CUSTOM_1 { get; set; }
        public string HEADER_CUSTOM_2 { get; set; }
        public string HEADER_CUSTOM_3 { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
