//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_SYS_LOG
    {
        public int LOG_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public string ACTION { get; set; }
        public string NEW_VALUE { get; set; }
        public string OLD_VALUE { get; set; }
        public string ERROR_MSG { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
