//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_MOCKUP_PROCESS_WAREHOUSE_BY_PG
    {
        public int MOCKUP_PROCESS_WAREHOUSE_BY_PG_ID { get; set; }
        public int MOCKUP_ID { get; set; }
        public int MOCKUP_SUB_ID { get; set; }
        public string TEST_PACK_SIZING { get; set; }
        public string TEST_PACK_HARD_EASY { get; set; }
        public string SUPPLIER_PRIMARY_CONTAINER { get; set; }
        public string SUPPLIER_PRIMARY_LID { get; set; }
        public string SHIP_TO_FACTORY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
