//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_MOCKUP_CHECK_LIST
    {
        public int CHECK_LIST_ID { get; set; }
        public string CHECK_LIST_NO { get; set; }
        public Nullable<int> REFERENCE_REQUEST_ID { get; set; }
        public string REFERENCE_REQUEST_NO { get; set; }
        public string REFERENCE_REQUEST_TYPE { get; set; }
        public string TRF_REF_NO { get; set; }
        public string CHECK_LIST_FOR_DESIGN { get; set; }
        public string REQUEST_FOR_DIE_LINE { get; set; }
        public string PROJECT_NAME { get; set; }
        public Nullable<int> REVIEWER { get; set; }
        public Nullable<int> TYPE_OF_PRODUCT_ID { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<int> SOLD_TO_ID { get; set; }
        public Nullable<int> SHIP_TO_ID { get; set; }
        public Nullable<int> RD_PERSON_ID { get; set; }
        public Nullable<int> PRIMARY_TYPE_ID { get; set; }
        public string PRIMARY_TYPE_OTHER { get; set; }
        public Nullable<int> PRIMARY_SIZE_ID { get; set; }
        public string PRIMARY_SIZE_OTHER { get; set; }
        public Nullable<int> CONTAINER_TYPE_ID { get; set; }
        public string CONTAINER_TYPE_OTHER { get; set; }
        public Nullable<int> LID_TYPE_ID { get; set; }
        public string LID_TYPE_OTHER { get; set; }
        public Nullable<int> PACKING_STYLE_ID { get; set; }
        public string PACKING_STYLE_OTHER { get; set; }
        public Nullable<int> PACK_SIZE_ID { get; set; }
        public string PACK_SIZE_OTHER { get; set; }
        public string PRIMARY_MATERIAL { get; set; }
        public Nullable<System.DateTime> REQUEST_DELIVERY_DATE { get; set; }
        public string OTHER_REQUESTS { get; set; }
        public Nullable<int> BRAND_ID { get; set; }
        public string BRAND_OTHER { get; set; }
        public Nullable<int> BRAND_OEM_ID { get; set; }
        public string BRAND_OEM_OTHER { get; set; }
        public string REQUEST_PHYSICAL_MOCKUP { get; set; }
        public Nullable<int> TWO_P_ID { get; set; }
        public Nullable<int> THREE_P_ID { get; set; }
        public string REF_PRODUCT_CODE { get; set; }
        public string NOMINATED_CONTAINER_VENDOR { get; set; }
        public string NOMINATED_SPEC { get; set; }
        public Nullable<int> CUSTOMER_OTHER_ID { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public string IN_TRANSIT_TO { get; set; }
        public string VIA { get; set; }
    }
}
