//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_ARTWORK_PROCESS_PA_CATCHING_METHOD
    {
        public int ARTWORK_SUB_PA_CATCHING_METHOD_ID { get; set; }
        public Nullable<int> ARTWORK_SUB_ID { get; set; }
        public Nullable<int> ARTWORK_SUB_PA_ID { get; set; }
        public Nullable<int> CATCHING_METHOD_ID { get; set; }
        public string CATCHING_METHOD_OTHER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
