//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_ARTWORK_REQUEST_REFERENCE
    {
        public int ARTWORK_REFERENCE_ID { get; set; }
        public int ARTWORK_REQUEST_ID { get; set; }
        public string REFERENCE_NO { get; set; }
        public string NET_WEIGHT { get; set; }
        public string DRAINED_WEIGHT { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public string PRODUCT_TYPE { get; set; }
    }
}
