//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_ARTWORK_PROCESS_RD
    {
        public int ARTWORK_PROCESS_RD_ID { get; set; }
        public int ARTWORK_REQUEST_ID { get; set; }
        public int ARTWORK_SUB_ID { get; set; }
        public string ACTION_CODE { get; set; }
        public string IS_CONFIRED { get; set; }
        public string NUTRITION { get; set; }
        public string NUTRITION_COMMENT { get; set; }
        public string INGREDIENTS { get; set; }
        public string INGREDIENTS_COMMENT { get; set; }
        public string ANALYSIS { get; set; }
        public string ANALYSIS_COMMENT { get; set; }
        public string HEALTH_CLAIM { get; set; }
        public string HEALTH_CLAIM_COMMENT { get; set; }
        public string NUTRIENT_CLAIM { get; set; }
        public string NUTRIENT_CLAIM_COMMENT { get; set; }
        public Nullable<int> REASON_ID { get; set; }
        public string SPECIES { get; set; }
        public string SPECIES_COMMENT { get; set; }
        public string CATCHING_AREA { get; set; }
        public string CATCHING_AREA_COMMENT { get; set; }
        public string CHECK_DETAIL { get; set; }
        public string CHECK_DETAIL_COMMENT { get; set; }
        public string COMMENT { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
