//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_MOCKUP_CHECK_LIST_ITEM
    {
        public int MOCKUP_ID { get; set; }
        public int CHECK_LIST_ID { get; set; }
        public string MOCKUP_NO { get; set; }
        public Nullable<int> MOCKUP_STATUS { get; set; }
        public Nullable<int> PACKING_TYPE_ID { get; set; }
        public Nullable<int> PRINT_SYSTEM_ID { get; set; }
        public Nullable<int> NUMBER_OF_COLOR_ID { get; set; }
        public Nullable<int> BOX_COLOR_ID { get; set; }
        public Nullable<int> COATING_ID { get; set; }
        public string PURPOSE_OF { get; set; }
        public Nullable<int> STYLE_ID { get; set; }
        public string PACKING_TYPE_OTHER { get; set; }
        public string PRINT_SYSTEM_OTHER { get; set; }
        public string NUMBER_OF_COLOR_OTHER { get; set; }
        public string BOX_COLOR_OTHER { get; set; }
        public string COATING_OTHER { get; set; }
        public string STYLE_OTHER { get; set; }
        public Nullable<long> NODE_ID { get; set; }
        public string REMARK { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
