//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_MOCKUP_PROCESS_PG_PRICE_TEMPLATE_BY_PG
    {
        public int PRICE_TEMPLATE_VENDOR_ID { get; set; }
        public int MOCKUP_ID { get; set; }
        public int MOCKUP_SUB_ID { get; set; }
        public string COMMENT_BY_PG { get; set; }
        public string SKUS { get; set; }
        public string VOLUME { get; set; }
        public string SPECIAL_COLOR { get; set; }
        public Nullable<int> DIRECTION_OF_STICKER { get; set; }
        public Nullable<int> STYLE_OF_PRINTING { get; set; }
        public string STYLE_OF_PRINTING_OTHER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
