//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_M_STEP_MOCKUP
    {
        public int STEP_MOCKUP_ID { get; set; }
        public string STEP_MOCKUP_CODE { get; set; }
        public string STEP_MOCKUP_NAME { get; set; }
        public string STEP_MOCKUP_DESCRIPTION { get; set; }
        public Nullable<int> ROLE_ID_RESPONSE { get; set; }
        public Nullable<decimal> DURATION { get; set; }
        public Nullable<decimal> DURATION_EXTEND { get; set; }
        public string IS_ACTIVE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
