//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_M_EMAIL_TEMPLATE
    {
        public int EMAIL_TEMPLATE_ID { get; set; }
        public string EMAIL_TEMPLATE_CODE { get; set; }
        public string M_SUBJECT { get; set; }
        public string M_DEAR { get; set; }
        public string M_BODY_01 { get; set; }
        public string IS_ACTIVE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
