//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_SYS_LOG_INTERFACE
    {
        public int LOG_INTERFACE_ID { get; set; }
        public string MODULE { get; set; }
        public string FUNCTION_NAME { get; set; }
        public string INPUT_FOR_TRACE { get; set; }
        public string OUTPUT_FOR_TRACE { get; set; }
        public System.DateTime CALL_DATETIME { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
