//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_ARTWORK_ATTACHMENT
    {
        public int ARTWORK_ATTACHMENT_ID { get; set; }
        public int ARTWORK_REQUEST_ID { get; set; }
        public int ARTWORK_SUB_ID { get; set; }
        public Nullable<long> NODE_ID { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string EXTENSION { get; set; }
        public Nullable<long> SIZE { get; set; }
        public string CONTENT_TYPE { get; set; }
        public Nullable<int> STEP_ARTWORK_ID { get; set; }
        public Nullable<long> VERSION { get; set; }
        public string VERSION2 { get; set; }
        public string IS_INTERNAL { get; set; }
        public string IS_VENDOR { get; set; }
        public string IS_CUSTOMER { get; set; }
        public string IS_SYSTEM { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
