//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_WF_ARTWORK_PROCESS_PA_FAO_ZONE
    {
        public int ARTWORK_SUB_PA_FAO_ID { get; set; }
        public int ARTWORK_SUB_ID { get; set; }
        public int ARTWORK_SUB_PA_ID { get; set; }
        public int FAO_ZONE_ID { get; set; }
        public string FAO_ZONE_OTHER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
