//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARTWORKEntities : DbContext
    {
        public ARTWORKEntities()
            : base("name=ARTWORKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ART_M_DECISION_REASON> ART_M_DECISION_REASON { get; set; }
        public virtual DbSet<ART_M_DECISION_REASON_CONFIG> ART_M_DECISION_REASON_CONFIG { get; set; }
        public virtual DbSet<ART_M_MESSAGE> ART_M_MESSAGE { get; set; }
        public virtual DbSet<ART_M_POSITION> ART_M_POSITION { get; set; }
        public virtual DbSet<ART_M_ROLE> ART_M_ROLE { get; set; }
        public virtual DbSet<ART_M_USER_COMPANY> ART_M_USER_COMPANY { get; set; }
        public virtual DbSet<ART_M_USER_CUSTOMER> ART_M_USER_CUSTOMER { get; set; }
        public virtual DbSet<ART_M_USER_ROLE> ART_M_USER_ROLE { get; set; }
        public virtual DbSet<ART_M_USER_TYPE_OF_PRODUCT> ART_M_USER_TYPE_OF_PRODUCT { get; set; }
        public virtual DbSet<ART_M_USER_UPPER_LEVEL> ART_M_USER_UPPER_LEVEL { get; set; }
        public virtual DbSet<ART_M_USER_VENDOR> ART_M_USER_VENDOR { get; set; }
        public virtual DbSet<ART_SYS_ACTION> ART_SYS_ACTION { get; set; }
        public virtual DbSet<ART_SYS_LOG_INTERFACE> ART_SYS_LOG_INTERFACE { get; set; }
        public virtual DbSet<ART_SYS_RUNNING_NO> ART_SYS_RUNNING_NO { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_MARKETING> ART_WF_ARTWORK_PROCESS_MARKETING { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_MARKETING_BY_PA> ART_WF_ARTWORK_PROCESS_MARKETING_BY_PA { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PG_BY_PA> ART_WF_ARTWORK_PROCESS_PG_BY_PA { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PLANNING> ART_WF_ARTWORK_PROCESS_PLANNING { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PLANNING_BY_PA> ART_WF_ARTWORK_PROCESS_PLANNING_BY_PA { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PP_BY_PA> ART_WF_ARTWORK_PROCESS_PP_BY_PA { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_QC_BY_PA> ART_WF_ARTWORK_PROCESS_QC_BY_PA { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_WH> ART_WF_ARTWORK_PROCESS_WH { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_WH_BY_PA> ART_WF_ARTWORK_PROCESS_WH_BY_PA { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_REQUEST_COUNTRY> ART_WF_ARTWORK_REQUEST_COUNTRY { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_REQUEST_CUSTOMER_OTHER> ART_WF_ARTWORK_REQUEST_CUSTOMER_OTHER { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_REQUEST_PRODUCT> ART_WF_ARTWORK_REQUEST_PRODUCT { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_REQUEST_PRODUCTION_PLANT> ART_WF_ARTWORK_REQUEST_PRODUCTION_PLANT { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_REQUEST_RECIPIENT> ART_WF_ARTWORK_REQUEST_RECIPIENT { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_REQUEST_REFERENCE> ART_WF_ARTWORK_REQUEST_REFERENCE { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_REQUEST_SALES_ORDER> ART_WF_ARTWORK_REQUEST_SALES_ORDER { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_CHECK_LIST> ART_WF_MOCKUP_CHECK_LIST { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_CHECK_LIST_COUNTRY> ART_WF_MOCKUP_CHECK_LIST_COUNTRY { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_CHECK_LIST_CUSTOMER_OTHER> ART_WF_MOCKUP_CHECK_LIST_CUSTOMER_OTHER { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_CHECK_LIST_ITEM> ART_WF_MOCKUP_CHECK_LIST_ITEM { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_CHECK_LIST_PG> ART_WF_MOCKUP_CHECK_LIST_PG { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_CHECK_LIST_PRODUCT> ART_WF_MOCKUP_CHECK_LIST_PRODUCT { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_CHECK_LIST_PRODUCTION_PLANT> ART_WF_MOCKUP_CHECK_LIST_PRODUCTION_PLANT { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_CHECK_LIST_REFERENCE> ART_WF_MOCKUP_CHECK_LIST_REFERENCE { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_APPROVE_MATCHBOARD> ART_WF_MOCKUP_PROCESS_APPROVE_MATCHBOARD { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_CUSTOMER> ART_WF_MOCKUP_PROCESS_CUSTOMER { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_CUSTOMER_BY_PG> ART_WF_MOCKUP_PROCESS_CUSTOMER_BY_PG { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_PG_PRICE_TEMPLATE_BY_PG_SUP> ART_WF_MOCKUP_PROCESS_PG_PRICE_TEMPLATE_BY_PG_SUP { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_PG_PRICE_TEMPLATE_BY_VENDOR> ART_WF_MOCKUP_PROCESS_PG_PRICE_TEMPLATE_BY_VENDOR { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_PG_SELECT_VENDOR> ART_WF_MOCKUP_PROCESS_PG_SELECT_VENDOR { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_PLANNING> ART_WF_MOCKUP_PROCESS_PLANNING { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_PLANNING_BY_PG> ART_WF_MOCKUP_PROCESS_PLANNING_BY_PG { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_RD> ART_WF_MOCKUP_PROCESS_RD { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_RD_BY_PG> ART_WF_MOCKUP_PROCESS_RD_BY_PG { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_VENDOR> ART_WF_MOCKUP_PROCESS_VENDOR { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_VENDOR_BY_PG> ART_WF_MOCKUP_PROCESS_VENDOR_BY_PG { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_WAREHOUSE> ART_WF_MOCKUP_PROCESS_WAREHOUSE { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_WAREHOUSE_BY_PG> ART_WF_MOCKUP_PROCESS_WAREHOUSE_BY_PG { get; set; }
        public virtual DbSet<SAP_M_BRAND> SAP_M_BRAND { get; set; }
        public virtual DbSet<SAP_M_CHARACTERISTIC_ITEM> SAP_M_CHARACTERISTIC_ITEM { get; set; }
        public virtual DbSet<SAP_M_COMPANY> SAP_M_COMPANY { get; set; }
        public virtual DbSet<SAP_M_LONG_TEXT> SAP_M_LONG_TEXT { get; set; }
        public virtual DbSet<SAP_M_ORDER_BOM> SAP_M_ORDER_BOM { get; set; }
        public virtual DbSet<SAP_M_PLANT> SAP_M_PLANT { get; set; }
        public virtual DbSet<SAP_M_PO_IDOC> SAP_M_PO_IDOC { get; set; }
        public virtual DbSet<SAP_M_PO_IDOC_ITEM> SAP_M_PO_IDOC_ITEM { get; set; }
        public virtual DbSet<SAP_M_TYPE_OF_PRODUCT> SAP_M_TYPE_OF_PRODUCT { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PG> ART_WF_ARTWORK_PROCESS_PG { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_ATTACHMENT> ART_WF_MOCKUP_ATTACHMENT { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_RD_BY_QC> ART_WF_ARTWORK_PROCESS_RD_BY_QC { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_GM_MK> ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_GM_MK { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_GM_MK_BY_MK> ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_GM_MK_BY_MK { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_GM_QC> ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_GM_QC { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_GM_QC_BY_QC> ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_GM_QC_BY_QC { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_MK> ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_MK { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_PA> ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_PA { get; set; }
        public virtual DbSet<ART_WF_DELEGATE> ART_WF_DELEGATE { get; set; }
        public virtual DbSet<ART_M_VENDOR_MATGROUP> ART_M_VENDOR_MATGROUP { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_PG> ART_WF_MOCKUP_PROCESS_PG { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_ASSIGN_SO_HEADER> ART_WF_ARTWORK_PROCESS_ASSIGN_SO_HEADER { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_ASSIGN_SO_ITEM> ART_WF_ARTWORK_PROCESS_ASSIGN_SO_ITEM { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_ASSIGN_SO_ITEM_COMPONENT> ART_WF_ARTWORK_PROCESS_ASSIGN_SO_ITEM_COMPONENT { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PA_CATCHING_AREA> ART_WF_ARTWORK_PROCESS_PA_CATCHING_AREA { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PA_FAO_ZONE> ART_WF_ARTWORK_PROCESS_PA_FAO_ZONE { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PA_PLANT> ART_WF_ARTWORK_PROCESS_PA_PLANT { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PA_SYMBOL> ART_WF_ARTWORK_PROCESS_PA_SYMBOL { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_VENDOR_BY_PA> ART_WF_ARTWORK_PROCESS_VENDOR_BY_PA { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PP> ART_WF_ARTWORK_PROCESS_PP { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_VENDOR> ART_WF_ARTWORK_PROCESS_VENDOR { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_VENDOR_BY_PP> ART_WF_ARTWORK_PROCESS_VENDOR_BY_PP { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_VENDOR_PO> ART_WF_ARTWORK_PROCESS_VENDOR_PO { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_CUSTOMER> ART_WF_ARTWORK_PROCESS_CUSTOMER { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_QC_BY_MK> ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_QC_BY_MK { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_SO_DETAIL> ART_WF_ARTWORK_PROCESS_SO_DETAIL { get; set; }
        public virtual DbSet<ART_SYS_LOG_EMAIL> ART_SYS_LOG_EMAIL { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_PA_BY_MK> ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_PA_BY_MK { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_MK_BY_QC> ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_MK_BY_QC { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_QC> ART_WF_ARTWORK_PROCESS_AFTER_CUSTOMER_QC { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_REQUEST_SALES_ORDER_REPEAT> ART_WF_ARTWORK_REQUEST_SALES_ORDER_REPEAT { get; set; }
        public virtual DbSet<SAP_M_COUNTRY> SAP_M_COUNTRY { get; set; }
        public virtual DbSet<ART_M_PERMISSION> ART_M_PERMISSION { get; set; }
        public virtual DbSet<V_ART_WAREHOUSE_REPORT> V_ART_WAREHOUSE_REPORT { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PA> ART_WF_ARTWORK_PROCESS_PA { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_ATTACHMENT> ART_WF_ARTWORK_ATTACHMENT { get; set; }
        public virtual DbSet<ART_M_USER> ART_M_USER { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_PG_PRICE_TEMPLATE_BY_PG> ART_WF_MOCKUP_PROCESS_PG_PRICE_TEMPLATE_BY_PG { get; set; }
        public virtual DbSet<ART_WF_LOG_DELEGATE> ART_WF_LOG_DELEGATE { get; set; }
        public virtual DbSet<ART_WF_LOG_REASSIGN> ART_WF_LOG_REASSIGN { get; set; }
        public virtual DbSet<ART_WF_LOG_REOPEN> ART_WF_LOG_REOPEN { get; set; }
        public virtual DbSet<ART_WF_LOG_CHANGE_OWNER> ART_WF_LOG_CHANGE_OWNER { get; set; }
        public virtual DbSet<SAP_M_PO_COMPLETE_SO_ITEM_COMPONENT> SAP_M_PO_COMPLETE_SO_ITEM_COMPONENT { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_ASSIGN_SO_LONG_TEXT> ART_WF_ARTWORK_PROCESS_ASSIGN_SO_LONG_TEXT { get; set; }
        public virtual DbSet<ART_M_POSITION_ROLE> ART_M_POSITION_ROLE { get; set; }
        public virtual DbSet<ART_M_PIC> ART_M_PIC { get; set; }
        public virtual DbSet<ART_M_RECEIVE_EMAIL_NEW_CUSTOMER> ART_M_RECEIVE_EMAIL_NEW_CUSTOMER { get; set; }
        public virtual DbSet<SAP_M_PO_COMPLETE_SO_ITEM> SAP_M_PO_COMPLETE_SO_ITEM { get; set; }
        public virtual DbSet<ART_M_TEMPLATE> ART_M_TEMPLATE { get; set; }
        public virtual DbSet<SAP_M_2P> SAP_M_2P { get; set; }
        public virtual DbSet<SAP_M_3P> SAP_M_3P { get; set; }
        public virtual DbSet<SAP_M_CHARACTERISTIC> SAP_M_CHARACTERISTIC { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS_PG_PRICE_TEMPLATE> ART_WF_MOCKUP_PROCESS_PG_PRICE_TEMPLATE { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_REQUEST> ART_WF_ARTWORK_REQUEST { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_REQUEST_ITEM> ART_WF_ARTWORK_REQUEST_ITEM { get; set; }
        public virtual DbSet<V_ART_ASSIGNED_SO> V_ART_ASSIGNED_SO { get; set; }
        public virtual DbSet<SAP_M_MATERIAL_CONVERSION> SAP_M_MATERIAL_CONVERSION { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_MATERIAL_LOCK_LOG> ART_WF_ARTWORK_MATERIAL_LOCK_LOG { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_MATERIAL_LOCK_DETAIL> ART_WF_ARTWORK_MATERIAL_LOCK_DETAIL { get; set; }
        public virtual DbSet<ART_M_PRINTING_STYLE> ART_M_PRINTING_STYLE { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_MATERIAL_LOCK> ART_WF_ARTWORK_MATERIAL_LOCK { get; set; }
        public virtual DbSet<SAP_M_PO_COMPLETE_SO_HEADER> SAP_M_PO_COMPLETE_SO_HEADER { get; set; }
        public virtual DbSet<V_SAP_SALES_ORDER> V_SAP_SALES_ORDER { get; set; }
        public virtual DbSet<XECM_M_PRODUCT> XECM_M_PRODUCT { get; set; }
        public virtual DbSet<XECM_M_PRODUCT5> XECM_M_PRODUCT5 { get; set; }
        public virtual DbSet<XECM_M_CUSTOMER> XECM_M_CUSTOMER { get; set; }
        public virtual DbSet<XECM_M_VENDOR> XECM_M_VENDOR { get; set; }
        public virtual DbSet<V_ART_SEARCH_DIELINE> V_ART_SEARCH_DIELINE { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_MAPPING_PO> ART_WF_ARTWORK_MAPPING_PO { get; set; }
        public virtual DbSet<IGRID_M_OUTBOUND_HEADER> IGRID_M_OUTBOUND_HEADER { get; set; }
        public virtual DbSet<ART_M_EMAIL_TEMPLATE> ART_M_EMAIL_TEMPLATE { get; set; }
        public virtual DbSet<ART_M_STEP_ARTWORK> ART_M_STEP_ARTWORK { get; set; }
        public virtual DbSet<ART_M_STEP_MOCKUP> ART_M_STEP_MOCKUP { get; set; }
        public virtual DbSet<ART_WF_MOCKUP_PROCESS> ART_WF_MOCKUP_PROCESS { get; set; }
        public virtual DbSet<V_ART_WF_DASHBOARD> V_ART_WF_DASHBOARD { get; set; }
        public virtual DbSet<V_ART_WF_DASHBOARD_ARTWORK> V_ART_WF_DASHBOARD_ARTWORK { get; set; }
        public virtual DbSet<ART_WF_REMARK_REASON_OTHER> ART_WF_REMARK_REASON_OTHER { get; set; }
        public virtual DbSet<ART_M_CONFIGURATION> ART_M_CONFIGURATION { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS> ART_WF_ARTWORK_PROCESS { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_CUSTOMER_BY_PA> ART_WF_ARTWORK_PROCESS_CUSTOMER_BY_PA { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_QC> ART_WF_ARTWORK_PROCESS_QC { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_RD> ART_WF_ARTWORK_PROCESS_RD { get; set; }
        public virtual DbSet<V_ART_WF_ALL_PROCESS> V_ART_WF_ALL_PROCESS { get; set; }
        public virtual DbSet<IGRID_M_OUTBOUND_ITEM> IGRID_M_OUTBOUND_ITEM { get; set; }
        public virtual DbSet<V_ART_ENDTOEND_REPORT> V_ART_ENDTOEND_REPORT { get; set; }
        public virtual DbSet<ART_SYS_LOG> ART_SYS_LOG { get; set; }
        public virtual DbSet<V_SAP_M_ORDER_BOM> V_SAP_M_ORDER_BOM { get; set; }
        public virtual DbSet<V_SAP_SALES_ORDER_ALL> V_SAP_SALES_ORDER_ALL { get; set; }
        public virtual DbSet<ART_TEMP_CONTAIN> ART_TEMP_CONTAIN { get; set; }
        public virtual DbSet<XECM_M_CONSTANT> XECM_M_CONSTANT { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PA_PRODUCT> ART_WF_ARTWORK_PROCESS_PA_PRODUCT { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PA_PRODUCT_OTHER> ART_WF_ARTWORK_PROCESS_PA_PRODUCT_OTHER { get; set; }
        public virtual DbSet<ART_WF_ARTWORK_PROCESS_PA_CATCHING_METHOD> ART_WF_ARTWORK_PROCESS_PA_CATCHING_METHOD { get; set; }
        public virtual DbSet<SAP_M_PO_COMPLETE_SO_HEADER_TMP> SAP_M_PO_COMPLETE_SO_HEADER_TMP { get; set; }
        public virtual DbSet<SAP_M_PO_COMPLETE_SO_ITEM_COMPONENT_TMP> SAP_M_PO_COMPLETE_SO_ITEM_COMPONENT_TMP { get; set; }
        public virtual DbSet<SAP_M_PO_COMPLETE_SO_ITEM_TMP> SAP_M_PO_COMPLETE_SO_ITEM_TMP { get; set; }
        public virtual DbSet<V_SAP_SALES_ORDER2> V_SAP_SALES_ORDER2 { get; set; }
        public virtual DbSet<ART_M_CONSTANT> ART_M_CONSTANT { get; set; }
    }
}
