//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IGRID_M_OUTBOUND_ITEM
    {
        public int IGRID_OUTBOUND_ITEM_ID { get; set; }
        public string ARTWORK_NO { get; set; }
        public string DATE { get; set; }
        public string TIME { get; set; }
        public string CHARACTERISTIC_NAME { get; set; }
        public string CHARACTERISTIC_VALUE { get; set; }
        public string CHARACTERISTIC_DESCRIPTION { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
