//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_M_3P
    {
        public int THREE_P_ID { get; set; }
        public string PRIMARY_SIZE_VALUE { get; set; }
        public string PRIMARY_SIZE_DESCRIPTION { get; set; }
        public string CONTAINER_TYPE_VALUE { get; set; }
        public string CONTAINER_TYPE_DESCRIPTION { get; set; }
        public string LID_TYPE_VALUE { get; set; }
        public string LID_TYPE_DESCRIPTION { get; set; }
        public string IS_ACTIVE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
