//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_M_ORDER_BOM
    {
        public int ORDER_BOM_ID { get; set; }
        public string CHANGE_TYPE { get; set; }
        public string DATE { get; set; }
        public string TIME { get; set; }
        public Nullable<decimal> COUNTER { get; set; }
        public string MATERIAL { get; set; }
        public string SOLD_TO_PARTY { get; set; }
        public string SHIP_TO_PARTY { get; set; }
        public string BRAND_ID { get; set; }
        public string ADDITIONAL_BRAND_ID { get; set; }
        public string ROUTE { get; set; }
        public string INTRANSIT_PORT { get; set; }
        public string SALES_ORGANIZATION { get; set; }
        public string PLANT { get; set; }
        public string MATERIAL_NUMBER { get; set; }
        public string COUNTRY_KEY { get; set; }
        public Nullable<decimal> PACKAGING_QUANTITY { get; set; }
        public string PACKAGING_UNIT { get; set; }
        public Nullable<decimal> FG_QUANTITY { get; set; }
        public string FG_UNIT { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> WASTE_PERCENT { get; set; }
        public Nullable<decimal> COUNTER_REFERENCE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
