//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_M_LONG_TEXT
    {
        public int LONG_TEXT_ID { get; set; }
        public string TEXT_NAME { get; set; }
        public string TEXT_ID { get; set; }
        public string TEXT_LANGUAGE { get; set; }
        public int LINE_ID { get; set; }
        public string LINE_TEXT { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
