//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_M_PO_IDOC_ITEM
    {
        public int PO_IDOC_ITEM_ID { get; set; }
        public int PO_IDOC_ID { get; set; }
        public string PO_ITEM_NO { get; set; }
        public string RECORD_TYPE { get; set; }
        public string DELETION_INDICATOR { get; set; }
        public string QUANTITY { get; set; }
        public string ORDER_UNIT { get; set; }
        public string ORDER_PRICE_UNIT { get; set; }
        public string NET_ORDER_PRICE { get; set; }
        public string PRICE_UNIT { get; set; }
        public string AMOUNT { get; set; }
        public string MATERIAL_GROUP { get; set; }
        public Nullable<decimal> DENOMINATOR_QUANTITY_CONVERSION { get; set; }
        public Nullable<decimal> NUMERATOR_QUANTITY_CONVERSION { get; set; }
        public string PLANT { get; set; }
        public string METERIAL_NUMBER { get; set; }
        public string SHORT_TEXT { get; set; }
        public string DELIVERY_DATE { get; set; }
        public string SALES_DOCUMENT_NO { get; set; }
        public Nullable<decimal> SALES_DOCUMENT_ITEM { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
