//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ART_ENDTOEND_REPORT
    {
        public long NUM { get; set; }
        public int WF_ID { get; set; }
        public int REQUEST_ID { get; set; }
        public int WF_SUB_ID { get; set; }
        public Nullable<int> PARENT_SUB_ID { get; set; }
        public string IS_END { get; set; }
        public string WF_TYPE { get; set; }
        public Nullable<int> CURRENT_STEP_ID { get; set; }
        public Nullable<int> CURRENT_USER_ID { get; set; }
        public Nullable<int> CURRENT_ROLE_ID { get; set; }
        public Nullable<int> CURRENT_VENDOR_ID { get; set; }
        public Nullable<int> CURRENT_CUSTOMER_ID { get; set; }
        public Nullable<int> REASON_ID { get; set; }
        public string IS_TERMINATE { get; set; }
        public string IS_DELEGATE { get; set; }
        public string REQUEST_NO { get; set; }
        public string WF_NO { get; set; }
        public System.DateTime REQUEST_CREATE_DATE { get; set; }
        public string PACKAGING_TYPE { get; set; }
        public string WF_STAUTS { get; set; }
        public string ORDER_BOM_COMPONENT { get; set; }
        public string CURRENT_STEP_NAME_1 { get; set; }
        public string CURRENT_USER_NAME_1 { get; set; }
        public Nullable<int> DURATION_1 { get; set; }
        public Nullable<System.DateTime> DUE_DATE_1 { get; set; }
        public string SALES_ORDER_NO { get; set; }
        public string BRAND_NAME { get; set; }
        public string ADDITIONAL_BRAND_NAME { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string PROD_INSP_MEMO { get; set; }
        public string REFERENCE_NO { get; set; }
        public string PLANT { get; set; }
        public string SOLD_TO { get; set; }
        public string SHIP_TO { get; set; }
        public string COUNTRY { get; set; }
        public string PORT { get; set; }
        public string IN_TRANSIT_TO { get; set; }
        public string CREATE_ON { get; set; }
        public string RDD { get; set; }
        public string PA_NAME { get; set; }
        public string PG_NAME { get; set; }
        public string CURRENT_STEP_NAME { get; set; }
        public string CURRENT_USER_NAME { get; set; }
        public Nullable<decimal> DURATION { get; set; }
        public System.DateTime STEP_CREATE_DATE { get; set; }
        public Nullable<System.DateTime> STEP_END_DATE { get; set; }
        public Nullable<int> USE_DAY { get; set; }
        //public Nullable<int> USEDAY { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<int> TOTAL_DAY { get; set; }
        //public Nullable<int> TOTALDAY { get; set; }
        public string REASON { get; set; }
        public string PROJECT_NAME { get; set; }
        public string CREATOR_NAME { get; set; }
        public string MARKETTING { get; set; }
        public string PRIMARY_TYPE_TXT { get; set; }
        public Nullable<int> REFERENCE_REQUEST_ID { get; set; }
        public string REFERENCE_REQUEST_NO { get; set; }
        public string REFERENCE_REQUEST_TYPE { get; set; }
        public Nullable<int> TYPE_OF_PRODUCT_ID { get; set; }
        public Nullable<int> REVIEWER_ID { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<int> SOLD_TO_ID { get; set; }
        public Nullable<int> SHIP_TO_ID { get; set; }
        public Nullable<int> CUSTOMER_OTHER_ID { get; set; }
        public Nullable<int> PRIMARY_TYPE_ID { get; set; }
        public string PRIMARY_TYPE_OTHER { get; set; }
        public Nullable<int> PRIMARY_SIZE_ID { get; set; }
        public string PRIMARY_SIZE_OTHER { get; set; }
        public Nullable<int> CONTAINER_TYPE_ID { get; set; }
        public string CONTAINER_TYPE_OTHER { get; set; }
        public Nullable<int> LID_TYPE_ID { get; set; }
        public string LID_TYPE_OTHER { get; set; }
        public Nullable<int> PACKING_STYLE_ID { get; set; }
        public string PACKING_STYLE_OTHER { get; set; }
        public Nullable<int> PACK_SIZE_ID { get; set; }
        public string PACK_SIZE_OTHER { get; set; }
        public Nullable<int> BRAND_ID { get; set; }
        public string BRAND_OTHER { get; set; }
        public Nullable<System.DateTime> REQUEST_DELIVERY_DATE { get; set; }
        public string SPECIAL_REQUIREMENT { get; set; }
        public string OTHER_REQUEST { get; set; }
        public Nullable<long> REQUEST_FORM_FOLDER_NODE_ID { get; set; }
        public Nullable<int> TWO_P_ID { get; set; }
        public Nullable<int> THREE_P_ID { get; set; }
        public Nullable<int> UPLOAD_BY { get; set; }
        public Nullable<System.DateTime> REQUEST_FORM_CREATE_DATE { get; set; }
        public string REMARK_KILLPROCESS { get; set; }
        public Nullable<int> TERMINATE_REASON_CODE { get; set; }
        public string IS_STEP_DURATION_EXTEND { get; set; }
        public Nullable<decimal> DURATION_STANDARD { get; set; }
        public string VENDOR_NAME { get; set; }
        public string CUSTOMER_NAME { get; set; }
    }
}
