//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ART_WAREHOUSE_REPORT
    {
        public long NUM { get; set; }
        public string SALES_ORG { get; set; }
        public string SALES_ORDER_NO { get; set; }
        public Nullable<decimal> SALES_ORDER_ITEM { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string MATERIAL_CODE { get; set; }
        public string MATERIAL_DECRIPTION { get; set; }
        public Nullable<int> PACKAGING_TYPE_ID { get; set; }
        public string PACKAGING_TYPE_NAME { get; set; }
        public string REQUEST_ITEM_NO { get; set; }
        public Nullable<int> BRAND_ID { get; set; }
        public string BRAND_NAME { get; set; }
        public string PROJECT_NAME { get; set; }
        public Nullable<int> SOLD_TO_ID { get; set; }
        public string SOLD_TO { get; set; }
        public string SOLD_TO_NAME { get; set; }
        public Nullable<int> SHIP_TO_ID { get; set; }
        public string SHIP_TO { get; set; }
        public string SHIP_TO_NAME { get; set; }
        public string PORT { get; set; }
        public string PURCHASE_ORDER_NO { get; set; }
        public string PO_ITEM_NO { get; set; }
        public string PURCHASING_ORG { get; set; }
        public string VENDOR_NO { get; set; }
        public string VENDOR_NAME { get; set; }
        public string DOC_DATE { get; set; }
        public string DELIVERY_DATE { get; set; }
        public string QUANTITY { get; set; }
        public string ORDER_UNIT { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<int> ARTWORK_SUB_ID { get; set; }
        public int PO_COMPLETE_SO_HEADER_ID { get; set; }
    }
}
