//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ART_SEARCH_DIELINE
    {
        public long NUM { get; set; }
        public string CHECK_LIST_NO { get; set; }
        public string MOCKUP_NO { get; set; }
        public string PRIMARY_TYPE_DISPLAY_TXT { get; set; }
        public string PRIMARY_SIZE_DISPLAY_TXT { get; set; }
        public string CONTAINER_TYPE_DISPLAY_TXT { get; set; }
        public string LID_TYPE_DISPLAY_TXT { get; set; }
        public string PACKING_STYLE_DISPLAY_TXT { get; set; }
        public string PACK_SIZE_DISPLAY_TXT { get; set; }
        public string PACKAGING_TYPE_DISPLAY_TXT { get; set; }
        public string VENDOR_DISPLAY_TXT { get; set; }
        public string GRADE_OF_DISPLAY_TXT { get; set; }
        public string DIMENSION_OF_DISPLAY_TXT { get; set; }
        public string SHEET_SIZE { get; set; }
        public string FLUTE_DISPLAY_TXT { get; set; }
        public string STYLE_DISPLAY_TXT { get; set; }
        public string TERMINATED_DISPLAY_TXT { get; set; }
        public string STATUS_DISPLAY_TXT { get; set; }
        public string NUMBER_OF_COLOR_DISPLAY_TXT { get; set; }
        public string STYLE_OF_PRINTING_DISPLAY_TXT { get; set; }
        public int CHECK_LIST_ID { get; set; }
        public int MOCKUP_ID { get; set; }
        public int MOCKUP_SUB_ID { get; set; }
        public Nullable<int> PRIMARY_TYPE_ID { get; set; }
        public Nullable<int> PACKING_TYPE_ID { get; set; }
        public Nullable<int> VENDOR { get; set; }
        public Nullable<int> GRADE_OF { get; set; }
        public Nullable<int> FLUTE { get; set; }
        public Nullable<int> STYLE_ID { get; set; }
        public Nullable<int> NUMBER_OF_COLOR_ID { get; set; }
        public Nullable<int> STYLE_OF_PRINTING { get; set; }
    }
}
