//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ART_WF_DASHBOARD_ARTWORK
    {
        public long NUM { get; set; }
        public Nullable<int> REFERENCE_REQUEST_ID { get; set; }
        public string REFERENCE_REQUEST_NO { get; set; }
        public string REFERENCE_REQUEST_TYPE { get; set; }
        public string TYPE_OF_ARTWORK { get; set; }
        public string ARTWORK_REQUEST_NO { get; set; }
        public string PROJECT_NAME { get; set; }
        public Nullable<int> TYPE_OF_PRODUCT_ID { get; set; }
        public Nullable<int> REVIEWER_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<int> SOLD_TO_ID { get; set; }
        public Nullable<int> SHIP_TO_ID { get; set; }
        public Nullable<int> CUSTOMER_OTHER_ID { get; set; }
        public Nullable<int> PRIMARY_TYPE_ID { get; set; }
        public string PRIMARY_TYPE_OTHER { get; set; }
        public Nullable<int> PRIMARY_SIZE_ID { get; set; }
        public string PRIMARY_SIZE_OTHER { get; set; }
        public Nullable<int> CONTAINER_TYPE_ID { get; set; }
        public string CONTAINER_TYPE_OTHER { get; set; }
        public Nullable<int> LID_TYPE_ID { get; set; }
        public string LID_TYPE_OTHER { get; set; }
        public Nullable<int> PACKING_STYLE_ID { get; set; }
        public string PACKING_STYLE_OTHER { get; set; }
        public Nullable<int> PACK_SIZE_ID { get; set; }
        public string PACK_SIZE_OTHER { get; set; }
        public Nullable<int> BRAND_ID { get; set; }
        public string BRAND_OTHER { get; set; }
        public Nullable<System.DateTime> REQUEST_DELIVERY_DATE { get; set; }
        public string SPECIAL_REQUIREMENT { get; set; }
        public string OTHER_REQUEST { get; set; }
        public Nullable<int> TWO_P_ID { get; set; }
        public Nullable<int> THREE_P_ID { get; set; }
        public System.DateTime CREATE_DATE_ARTWORK_REQUEST { get; set; }
        public int CREATE_BY_ARTWORK_REQUEST { get; set; }
        public int ARTWORK_ITEM_ID { get; set; }
        public string REQUEST_ITEM_NO { get; set; }
        public string SOLD_TO_DISPLAY_TXT { get; set; }
        public string SHIP_TO_DISPLAY_TXT { get; set; }
        public string BRAND_DISPLAY_TXT { get; set; }
        public Nullable<int> CURRENT_STEP_ID { get; set; }
        public Nullable<int> CURRENT_USER_ID { get; set; }
        public Nullable<int> CURRENT_ROLE_ID { get; set; }
        public Nullable<int> CURRENT_VENDOR_ID { get; set; }
        public Nullable<int> CURRENT_CUSTOMER_ID { get; set; }
        public string REMARK { get; set; }
        public string IS_END { get; set; }
        public Nullable<int> REASON_ID { get; set; }
        public string CREATE_BY_PROCESS_TITLE { get; set; }
        public string CREATE_BY_PROCESS_FIRST_NAME { get; set; }
        public string CREATE_BY_PROCESS_LAST_NAME { get; set; }
        public string CURRENT_STEP_DISPLAY_TXT { get; set; }
        public string CREATE_BY_ARTWORK_REQUEST_TITLE { get; set; }
        public string CREATE_BY_ARTWORK_REQUEST_FIRST_NAME { get; set; }
        public string CREATE_BY_ARTWORK_REQUEST_LAST_NAME { get; set; }
        public int ARTWORK_SUB_ID { get; set; }
        public Nullable<int> PARENT_ARTWORK_SUB_ID { get; set; }
        public int ARTWORK_REQUEST_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE_PROCESS { get; set; }
        public Nullable<int> CREATE_BY_PROCESS { get; set; }
        public string REMARK_TERMINATE { get; set; }
        public string IS_DELEGATE { get; set; }
        public string IS_TERMINATE { get; set; }
        public Nullable<decimal> DURATION { get; set; }
        public Nullable<decimal> DURATION_EXTEND { get; set; }
        public string STEP_ARTWORK_DESCRIPTION { get; set; }
        public string STEP_ARTWORK_CODE { get; set; }
        public Nullable<int> ROLE_ID_RESPONSE { get; set; }
        public string REMARK_KILLPROCESS { get; set; }
        public string IS_STEP_DURATION_EXTEND { get; set; }
    }
}
