//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ART_WF_DASHBOARD
    {
        public long NUM { get; set; }
        public int CHECK_LIST_ID { get; set; }
        public string CHECK_LIST_NO { get; set; }
        public string TRF_REF_NO { get; set; }
        public Nullable<int> TYPE_OF_PRODUCT_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<int> SOLD_TO_ID { get; set; }
        public Nullable<int> SHIP_TO_ID { get; set; }
        public Nullable<int> RD_PERSON_ID { get; set; }
        public Nullable<int> PRIMARY_TYPE_ID { get; set; }
        public string PRIMARY_TYPE_OTHER { get; set; }
        public Nullable<int> PRIMARY_SIZE_ID { get; set; }
        public string PRIMARY_SIZE_OTHER { get; set; }
        public Nullable<int> CONTAINER_TYPE_ID { get; set; }
        public string CONTAINER_TYPE_OTHER { get; set; }
        public Nullable<int> LID_TYPE_ID { get; set; }
        public string LID_TYPE_OTHER { get; set; }
        public Nullable<int> PACKING_STYLE_ID { get; set; }
        public string PACKING_STYLE_OTHER { get; set; }
        public Nullable<int> PACK_SIZE_ID { get; set; }
        public string PACK_SIZE_OTHER { get; set; }
        public string PRIMARY_MATERIAL { get; set; }
        public Nullable<System.DateTime> REQUEST_DELIVERY_DATE { get; set; }
        public string OTHER_REQUESTS { get; set; }
        public Nullable<int> BRAND_ID { get; set; }
        public string BRAND_OTHER { get; set; }
        public Nullable<int> BRAND_OEM_ID { get; set; }
        public string BRAND_OEM_OTHER { get; set; }
        public string REQUEST_PHYSICAL_MOCKUP { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public string MOCKUP_NO { get; set; }
        public Nullable<int> MOCKUP_STATUS { get; set; }
        public Nullable<int> PACKING_TYPE_ID { get; set; }
        public Nullable<int> PRINT_SYSTEM_ID { get; set; }
        public Nullable<int> NUMBER_OF_COLOR_ID { get; set; }
        public Nullable<int> BOX_COLOR_ID { get; set; }
        public Nullable<int> COATING_ID { get; set; }
        public string PURPOSE_OF { get; set; }
        public Nullable<int> STYLE_ID { get; set; }
        public string PACKING_TYPE_OTHER { get; set; }
        public string PRINT_SYSTEM_OTHER { get; set; }
        public string NUMBER_OF_COLOR_OTHER { get; set; }
        public string BOX_COLOR_OTHER { get; set; }
        public string STYLE_OTHER { get; set; }
        public string COATING_OTHER { get; set; }
        public int MOCKUP_ID { get; set; }
        public int MOCKUP_SUB_ID { get; set; }
        public Nullable<int> CURRENT_STEP_ID { get; set; }
        public Nullable<int> CURRENT_ROLE_ID { get; set; }
        public Nullable<int> CURRENT_USER_ID { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> CREATE_DATE_PROCESS { get; set; }
        public System.DateTime CREATE_DATE_CHECK_LIST { get; set; }
        public Nullable<int> CREATE_BY_PROCESS { get; set; }
        public int CREATE_BY_CHECK_LIST { get; set; }
        public string IS_END { get; set; }
        public Nullable<int> PARENT_MOCKUP_SUB_ID { get; set; }
        public Nullable<long> NODE_ID { get; set; }
        public string CHECK_LIST_FOR_DESIGN { get; set; }
        public string REQUEST_FOR_DIE_LINE { get; set; }
        public string PROJECT_NAME { get; set; }
        public Nullable<int> REVIEWER { get; set; }
        public Nullable<int> TWO_P_ID { get; set; }
        public Nullable<int> THREE_P_ID { get; set; }
        public string REF_PRODUCT_CODE { get; set; }
        public Nullable<int> CURRENT_VENDOR_ID { get; set; }
        public Nullable<int> CURRENT_CUSTOMER_ID { get; set; }
        public string NOMINATED_SPEC { get; set; }
        public string NOMINATED_CONTAINER_VENDOR { get; set; }
        public Nullable<int> CUSTOMER_OTHER_ID { get; set; }
        public string SOLD_TO_DISPLAY_TXT { get; set; }
        public string SHIP_TO_DISPLAY_TXT { get; set; }
        public string BRAND_DISPLAY_TXT { get; set; }
        public string PACKING_TYPE_DISPLAY_TXT { get; set; }
        public string CREATE_BY_CHECK_LIST_TITLE { get; set; }
        public string CREATE_BY_CHECK_LIST_FIRST_NAME { get; set; }
        public string CREATE_BY_CHECK_LIST_LAST_NAME { get; set; }
        public string CREATE_BY_PROCESS_TITLE { get; set; }
        public string CREATE_BY_PROCESS_FIRST_NAME { get; set; }
        public string CREATE_BY_PROCESS_LAST_NAME { get; set; }
        public string CURRENT_STEP_DISPLAY_TXT { get; set; }
        public Nullable<int> REFERENCE_REQUEST_ID { get; set; }
        public string REFERENCE_REQUEST_NO { get; set; }
        public string REFERENCE_REQUEST_TYPE { get; set; }
        public Nullable<int> REASON_ID { get; set; }
        public Nullable<decimal> DURATION { get; set; }
        public Nullable<decimal> DURATION_EXTEND { get; set; }
        public string STEP_MOCKUP_DESCRIPTION { get; set; }
        public string IS_TERMINATE { get; set; }
        public string REMARK_TERMINATE { get; set; }
        public string IS_DELEGATE { get; set; }
        public string STEP_MOCKUP_CODE { get; set; }
        public Nullable<int> ROLE_ID_RESPONSE { get; set; }
        public string REMARK_KILLPROCESS { get; set; }
        public string IS_STEP_DURATION_EXTEND { get; set; }
    }
}
