//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SAP_SALES_ORDER2
    {
        public Nullable<long> NUM { get; set; }
        public int PO_COMPLETE_SO_HEADER_ID { get; set; }
        public string SALES_ORDER_NO { get; set; }
        public string SOLD_TO { get; set; }
        public string SOLD_TO_NAME { get; set; }
        public Nullable<decimal> LAST_SHIPMENT_DATE { get; set; }
        public Nullable<decimal> DATE_1_2 { get; set; }
        public Nullable<System.DateTime> CREATE_ON { get; set; }
        public Nullable<System.DateTime> RDD { get; set; }
        public string PAYMENT_TERM { get; set; }
        public string LC_NO { get; set; }
        public Nullable<decimal> EXPIRED_DATE { get; set; }
        public string SHIP_TO { get; set; }
        public string SHIP_TO_NAME { get; set; }
        public string SOLD_TO_PO { get; set; }
        public string SHIP_TO_PO { get; set; }
        public string SALES_GROUP { get; set; }
        public string MARKETING_CO { get; set; }
        public string MARKETING_CO_NAME { get; set; }
        public string MARKETING { get; set; }
        public string MARKETING_NAME { get; set; }
        public string MARKETING_ORDER_SAP { get; set; }
        public string MARKETING_ORDER_SAP_NAME { get; set; }
        public string SALES_ORG { get; set; }
        public string DISTRIBUTION_CHANNEL { get; set; }
        public string DIVITION { get; set; }
        public string SALES_ORDER_TYPE { get; set; }
        public string HEADER_CUSTOM_1 { get; set; }
        public string HEADER_CUSTOM_2 { get; set; }
        public string HEADER_CUSTOM_3 { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public string IS_MIGRATION { get; set; }
        public Nullable<int> PO_COMPLETE_SO_ITEM_ID { get; set; }
        public Nullable<decimal> ITEM { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string MATERIAL_DESCRIPTION { get; set; }
        public string NET_WEIGHT { get; set; }
        public Nullable<decimal> ORDER_QTY { get; set; }
        public string ORDER_UNIT { get; set; }
        public Nullable<System.DateTime> ETD_DATE_FROM { get; set; }
        public Nullable<System.DateTime> ETD_DATE_TO { get; set; }
        public string PLANT { get; set; }
        public string OLD_MATERIAL_CODE { get; set; }
        public string PACK_SIZE { get; set; }
        public string VALUME_PER_UNIT { get; set; }
        public string VALUME_UNIT { get; set; }
        public string SIZE_DRAIN_WT { get; set; }
        public string PROD_INSP_MEMO { get; set; }
        public string REJECTION_CODE { get; set; }
        public string REJECTION_DESCRIPTION { get; set; }
        public string PORT { get; set; }
        public string VIA { get; set; }
        public string IN_TRANSIT_TO { get; set; }
        public string BRAND_ID { get; set; }
        public string BRAND_DESCRIPTION { get; set; }
        public string ADDITIONAL_BRAND_ID { get; set; }
        public string ADDITIONAL_BRAND_DESCRIPTION { get; set; }
        public string PRODUCTION_PLANT { get; set; }
        public string ZONE { get; set; }
        public string COUNTRY { get; set; }
        public string PRODUCTION_HIERARCHY { get; set; }
        public string MRP_CONTROLLER { get; set; }
        public string STOCK { get; set; }
        public string ITEM_CUSTOM_1 { get; set; }
        public string ITEM_CUSTOM_2 { get; set; }
        public string ITEM_CUSTOM_3 { get; set; }
        public Nullable<int> PO_COMPLETE_SO_ITEM_COMPONENT_ID { get; set; }
        public string COMPONENT_ITEM { get; set; }
        public string COMPONENT_MATERIAL { get; set; }
        public string DECRIPTION { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string UNIT { get; set; }
        public string BOM_STOCK { get; set; }
        public string BOM_ITEM_CUSTOM_1 { get; set; }
        public string BOM_ITEM_CUSTOM_2 { get; set; }
        public string BOM_ITEM_CUSTOM_3 { get; set; }
        public string BOM_IS_ACTIVE { get; set; }
        public string SO_ITEM_IS_ACTIVE { get; set; }
        public string BOM_QTY_STOCK { get; set; }
    }
}
