//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class XECM_M_CONSTANT
    {
        public int ID { get; set; }
        public string PROGRAM_NAME { get; set; }
        public string VARIABLE_NAME { get; set; }
        public string TYPE { get; set; }
        public string SEQUENCE { get; set; }
        public string FUNCAREA { get; set; }
        public string INEXCL { get; set; }
        public string OPTION { get; set; }
        public string LOWVALUE { get; set; }
        public string HIGHVALUE { get; set; }
        public string IS_ACTIVE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
    }
}
