//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class XECM_M_PRODUCT
    {
        public int XECM_PRODUCT_ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public string NET_WEIGHT { get; set; }
        public string DRAINED_WEIGHT { get; set; }
        public string PRIMARY_SIZE { get; set; }
        public string CONTAINER_TYPE { get; set; }
        public string LID_TYPE { get; set; }
        public string PACKING_STYLE { get; set; }
        public string PACK_SIZE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_CS { get; set; }
    }
}
