//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XECMData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTree
    {
        public long OwnerID { get; set; }
        public long ParentID { get; set; }
        public long DataID { get; set; }
        public string Name { get; set; }
        public long OriginOwnerID { get; set; }
        public long OriginDataID { get; set; }
        public long UserID { get; set; }
        public long GroupID { get; set; }
        public int UPermissions { get; set; }
        public int GPermissions { get; set; }
        public int WPermissions { get; set; }
        public int SPermissions { get; set; }
        public int ACLCount { get; set; }
        public Nullable<long> PermID { get; set; }
        public Nullable<long> DataType { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> MaxVers { get; set; }
        public Nullable<byte> Reserved { get; set; }
        public Nullable<long> ReservedBy { get; set; }
        public Nullable<System.DateTime> ReservedDate { get; set; }
        public Nullable<long> VersionNum { get; set; }
        public string DComment { get; set; }
        public string DCategory { get; set; }
        public Nullable<int> SubType { get; set; }
        public string ExAtt1 { get; set; }
        public string ExAtt2 { get; set; }
        public Nullable<long> Ordering { get; set; }
        public Nullable<long> Major { get; set; }
        public Nullable<long> Minor { get; set; }
        public Nullable<long> ReleaseRef { get; set; }
        public Nullable<long> ChildCount { get; set; }
        public Nullable<long> AssignedTo { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<System.DateTime> DateEffective { get; set; }
        public Nullable<System.DateTime> DateExpiration { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Priority { get; set; }
        public string GIF { get; set; }
        public string ExtendedData { get; set; }
        public Nullable<int> Catalog { get; set; }
        public Nullable<int> CacheExpiration { get; set; }
        public int Deleted { get; set; }
        public System.Guid GUID { get; set; }
    }
}
