//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XECMData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LLAttrData
    {
        public long ID { get; set; }
        public long VerNum { get; set; }
        public long DefID { get; set; }
        public long DefVerN { get; set; }
        public int AttrID { get; set; }
        public int AttrType { get; set; }
        public int CustomID { get; set; }
        public int EntryNum { get; set; }
        public long ParentKeyID { get; set; }
        public Nullable<long> KeyID { get; set; }
        public Nullable<long> ValInt { get; set; }
        public Nullable<decimal> ValReal { get; set; }
        public Nullable<System.DateTime> ValDate { get; set; }
        public string ValStr { get; set; }
        public string ValLong { get; set; }
    }
}
