//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLLTests.MM73_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MM73_ServiceReference.MM73")]
    public interface MM73 {
        
        // CODEGEN: Generating message contract since the operation MATERIAL_NUMBER is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="MATERIAL_NUMBER", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BLLTests.MM73_ServiceReference.MATERIAL_NUMBERResponse MATERIAL_NUMBER(BLLTests.MM73_ServiceReference.MATERIAL_NUMBERRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="MATERIAL_NUMBER", ReplyAction="*")]
        System.Threading.Tasks.Task<BLLTests.MM73_ServiceReference.MATERIAL_NUMBERResponse> MATERIAL_NUMBERAsync(BLLTests.MM73_ServiceReference.MATERIAL_NUMBERRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class MM73_OUTBOUND_MATERIAL_NUMBER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IGRID_OUTBOUND_MODEL paramField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IGRID_OUTBOUND_MODEL param {
            get {
                return this.paramField;
            }
            set {
                this.paramField = value;
                this.RaisePropertyChanged("param");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IGRID_OUTBOUND_MODEL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IGRID_OUTBOUND_HEADER_MODEL[] oUTBOUND_HEADERSField;
        
        private IGRID_OUTBOUND_ITEM_MODEL[] oUTBOUND_ITEMSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Header")]
        public IGRID_OUTBOUND_HEADER_MODEL[] OUTBOUND_HEADERS {
            get {
                return this.oUTBOUND_HEADERSField;
            }
            set {
                this.oUTBOUND_HEADERSField = value;
                this.RaisePropertyChanged("OUTBOUND_HEADERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("InboundArtwork")]
        public IGRID_OUTBOUND_ITEM_MODEL[] OUTBOUND_ITEMS {
            get {
                return this.oUTBOUND_ITEMSField;
            }
            set {
                this.oUTBOUND_ITEMSField = value;
                this.RaisePropertyChanged("OUTBOUND_ITEMS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IGRID_OUTBOUND_HEADER_MODEL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string artworkNumberField;
        
        private string recordTypeField;
        
        private string dateField;
        
        private string timeField;
        
        private string materialNumberField;
        
        private string materialDescriptionField;
        
        private string materialCreatedDateField;
        
        private string artworkURLField;
        
        private string statusField;
        
        private string pAUserNameField;
        
        private string pGUserNameField;
        
        private string referenceMaterialField;
        
        private string plantField;
        
        private string printingStyleofPrimaryField;
        
        private string printingStyleofSecondaryField;
        
        private string customersDesignField;
        
        private string customersDesignDetailField;
        
        private string customersSpecField;
        
        private string customersSpecDetailField;
        
        private string customersSizeField;
        
        private string customersSizeDetailField;
        
        private string customerNominatesVendorField;
        
        private string customerNominatesVendorDetailField;
        
        private string customerNominatesColorPantoneField;
        
        private string customerNominatesColorPantoneDetailField;
        
        private string customersBarcodeScanableField;
        
        private string customersBarcodeScanableDetailField;
        
        private string customersBarcodeSpecField;
        
        private string customersBarcodeSpecDetailField;
        
        private string firstInfoGroupField;
        
        private string sONumberField;
        
        private string sOitemField;
        
        private string sOPlantField;
        
        private string pICMKTField;
        
        private string destinationField;
        
        private string remarkNoteofPAField;
        
        private string finalInfoGroupField;
        
        private string remarkNoteofPGField;
        
        private string completeInfoGroupField;
        
        private string productionExpirydatesystemField;
        
        private string seriousnessofcolorprintingField;
        
        private string custIngreNutritionAnalysisField;
        
        private string shadeLimitField;
        
        private string packageQuantityField;
        
        private string wastePercentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ArtworkNumber {
            get {
                return this.artworkNumberField;
            }
            set {
                this.artworkNumberField = value;
                this.RaisePropertyChanged("ArtworkNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RecordType {
            get {
                return this.recordTypeField;
            }
            set {
                this.recordTypeField = value;
                this.RaisePropertyChanged("RecordType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MaterialNumber {
            get {
                return this.materialNumberField;
            }
            set {
                this.materialNumberField = value;
                this.RaisePropertyChanged("MaterialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MaterialDescription {
            get {
                return this.materialDescriptionField;
            }
            set {
                this.materialDescriptionField = value;
                this.RaisePropertyChanged("MaterialDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MaterialCreatedDate {
            get {
                return this.materialCreatedDateField;
            }
            set {
                this.materialCreatedDateField = value;
                this.RaisePropertyChanged("MaterialCreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ArtworkURL {
            get {
                return this.artworkURLField;
            }
            set {
                this.artworkURLField = value;
                this.RaisePropertyChanged("ArtworkURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PAUserName {
            get {
                return this.pAUserNameField;
            }
            set {
                this.pAUserNameField = value;
                this.RaisePropertyChanged("PAUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PGUserName {
            get {
                return this.pGUserNameField;
            }
            set {
                this.pGUserNameField = value;
                this.RaisePropertyChanged("PGUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ReferenceMaterial {
            get {
                return this.referenceMaterialField;
            }
            set {
                this.referenceMaterialField = value;
                this.RaisePropertyChanged("ReferenceMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
                this.RaisePropertyChanged("Plant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PrintingStyleofPrimary {
            get {
                return this.printingStyleofPrimaryField;
            }
            set {
                this.printingStyleofPrimaryField = value;
                this.RaisePropertyChanged("PrintingStyleofPrimary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PrintingStyleofSecondary {
            get {
                return this.printingStyleofSecondaryField;
            }
            set {
                this.printingStyleofSecondaryField = value;
                this.RaisePropertyChanged("PrintingStyleofSecondary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CustomersDesign {
            get {
                return this.customersDesignField;
            }
            set {
                this.customersDesignField = value;
                this.RaisePropertyChanged("CustomersDesign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CustomersDesignDetail {
            get {
                return this.customersDesignDetailField;
            }
            set {
                this.customersDesignDetailField = value;
                this.RaisePropertyChanged("CustomersDesignDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string CustomersSpec {
            get {
                return this.customersSpecField;
            }
            set {
                this.customersSpecField = value;
                this.RaisePropertyChanged("CustomersSpec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string CustomersSpecDetail {
            get {
                return this.customersSpecDetailField;
            }
            set {
                this.customersSpecDetailField = value;
                this.RaisePropertyChanged("CustomersSpecDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string CustomersSize {
            get {
                return this.customersSizeField;
            }
            set {
                this.customersSizeField = value;
                this.RaisePropertyChanged("CustomersSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string CustomersSizeDetail {
            get {
                return this.customersSizeDetailField;
            }
            set {
                this.customersSizeDetailField = value;
                this.RaisePropertyChanged("CustomersSizeDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string CustomerNominatesVendor {
            get {
                return this.customerNominatesVendorField;
            }
            set {
                this.customerNominatesVendorField = value;
                this.RaisePropertyChanged("CustomerNominatesVendor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string CustomerNominatesVendorDetail {
            get {
                return this.customerNominatesVendorDetailField;
            }
            set {
                this.customerNominatesVendorDetailField = value;
                this.RaisePropertyChanged("CustomerNominatesVendorDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string CustomerNominatesColorPantone {
            get {
                return this.customerNominatesColorPantoneField;
            }
            set {
                this.customerNominatesColorPantoneField = value;
                this.RaisePropertyChanged("CustomerNominatesColorPantone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string CustomerNominatesColorPantoneDetail {
            get {
                return this.customerNominatesColorPantoneDetailField;
            }
            set {
                this.customerNominatesColorPantoneDetailField = value;
                this.RaisePropertyChanged("CustomerNominatesColorPantoneDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string CustomersBarcodeScanable {
            get {
                return this.customersBarcodeScanableField;
            }
            set {
                this.customersBarcodeScanableField = value;
                this.RaisePropertyChanged("CustomersBarcodeScanable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string CustomersBarcodeScanableDetail {
            get {
                return this.customersBarcodeScanableDetailField;
            }
            set {
                this.customersBarcodeScanableDetailField = value;
                this.RaisePropertyChanged("CustomersBarcodeScanableDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string CustomersBarcodeSpec {
            get {
                return this.customersBarcodeSpecField;
            }
            set {
                this.customersBarcodeSpecField = value;
                this.RaisePropertyChanged("CustomersBarcodeSpec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string CustomersBarcodeSpecDetail {
            get {
                return this.customersBarcodeSpecDetailField;
            }
            set {
                this.customersBarcodeSpecDetailField = value;
                this.RaisePropertyChanged("CustomersBarcodeSpecDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string FirstInfoGroup {
            get {
                return this.firstInfoGroupField;
            }
            set {
                this.firstInfoGroupField = value;
                this.RaisePropertyChanged("FirstInfoGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string SONumber {
            get {
                return this.sONumberField;
            }
            set {
                this.sONumberField = value;
                this.RaisePropertyChanged("SONumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string SOitem {
            get {
                return this.sOitemField;
            }
            set {
                this.sOitemField = value;
                this.RaisePropertyChanged("SOitem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string SOPlant {
            get {
                return this.sOPlantField;
            }
            set {
                this.sOPlantField = value;
                this.RaisePropertyChanged("SOPlant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string PICMKT {
            get {
                return this.pICMKTField;
            }
            set {
                this.pICMKTField = value;
                this.RaisePropertyChanged("PICMKT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("Destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string RemarkNoteofPA {
            get {
                return this.remarkNoteofPAField;
            }
            set {
                this.remarkNoteofPAField = value;
                this.RaisePropertyChanged("RemarkNoteofPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string FinalInfoGroup {
            get {
                return this.finalInfoGroupField;
            }
            set {
                this.finalInfoGroupField = value;
                this.RaisePropertyChanged("FinalInfoGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string RemarkNoteofPG {
            get {
                return this.remarkNoteofPGField;
            }
            set {
                this.remarkNoteofPGField = value;
                this.RaisePropertyChanged("RemarkNoteofPG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string CompleteInfoGroup {
            get {
                return this.completeInfoGroupField;
            }
            set {
                this.completeInfoGroupField = value;
                this.RaisePropertyChanged("CompleteInfoGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string ProductionExpirydatesystem {
            get {
                return this.productionExpirydatesystemField;
            }
            set {
                this.productionExpirydatesystemField = value;
                this.RaisePropertyChanged("ProductionExpirydatesystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string Seriousnessofcolorprinting {
            get {
                return this.seriousnessofcolorprintingField;
            }
            set {
                this.seriousnessofcolorprintingField = value;
                this.RaisePropertyChanged("Seriousnessofcolorprinting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string CustIngreNutritionAnalysis {
            get {
                return this.custIngreNutritionAnalysisField;
            }
            set {
                this.custIngreNutritionAnalysisField = value;
                this.RaisePropertyChanged("CustIngreNutritionAnalysis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string ShadeLimit {
            get {
                return this.shadeLimitField;
            }
            set {
                this.shadeLimitField = value;
                this.RaisePropertyChanged("ShadeLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string PackageQuantity {
            get {
                return this.packageQuantityField;
            }
            set {
                this.packageQuantityField = value;
                this.RaisePropertyChanged("PackageQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string WastePercent {
            get {
                return this.wastePercentField;
            }
            set {
                this.wastePercentField = value;
                this.RaisePropertyChanged("WastePercent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SERVICE_RESULT_MODEL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IGRID_OUTBOUND_ITEM_MODEL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string artworkNumberField;
        
        private string dateField;
        
        private string timeField;
        
        private string characteristicField;
        
        private string valueField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ArtworkNumber {
            get {
                return this.artworkNumberField;
            }
            set {
                this.artworkNumberField = value;
                this.RaisePropertyChanged("ArtworkNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Characteristic {
            get {
                return this.characteristicField;
            }
            set {
                this.characteristicField = value;
                this.RaisePropertyChanged("Characteristic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class MM73_OUTBOUND_MATERIAL_NUMBERResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SERVICE_RESULT_MODEL mM73_OUTBOUND_MATERIAL_NUMBERResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SERVICE_RESULT_MODEL MM73_OUTBOUND_MATERIAL_NUMBERResult {
            get {
                return this.mM73_OUTBOUND_MATERIAL_NUMBERResultField;
            }
            set {
                this.mM73_OUTBOUND_MATERIAL_NUMBERResultField = value;
                this.RaisePropertyChanged("MM73_OUTBOUND_MATERIAL_NUMBERResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MATERIAL_NUMBERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BLLTests.MM73_ServiceReference.MM73_OUTBOUND_MATERIAL_NUMBER MM73_OUTBOUND_MATERIAL_NUMBER;
        
        public MATERIAL_NUMBERRequest() {
        }
        
        public MATERIAL_NUMBERRequest(BLLTests.MM73_ServiceReference.MM73_OUTBOUND_MATERIAL_NUMBER MM73_OUTBOUND_MATERIAL_NUMBER) {
            this.MM73_OUTBOUND_MATERIAL_NUMBER = MM73_OUTBOUND_MATERIAL_NUMBER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MATERIAL_NUMBERResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BLLTests.MM73_ServiceReference.MM73_OUTBOUND_MATERIAL_NUMBERResponse MM73_OUTBOUND_MATERIAL_NUMBERResponse;
        
        public MATERIAL_NUMBERResponse() {
        }
        
        public MATERIAL_NUMBERResponse(BLLTests.MM73_ServiceReference.MM73_OUTBOUND_MATERIAL_NUMBERResponse MM73_OUTBOUND_MATERIAL_NUMBERResponse) {
            this.MM73_OUTBOUND_MATERIAL_NUMBERResponse = MM73_OUTBOUND_MATERIAL_NUMBERResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MM73Channel : BLLTests.MM73_ServiceReference.MM73, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MM73Client : System.ServiceModel.ClientBase<BLLTests.MM73_ServiceReference.MM73>, BLLTests.MM73_ServiceReference.MM73 {
        
        public MM73Client() {
        }
        
        public MM73Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MM73Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MM73Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MM73Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLLTests.MM73_ServiceReference.MATERIAL_NUMBERResponse BLLTests.MM73_ServiceReference.MM73.MATERIAL_NUMBER(BLLTests.MM73_ServiceReference.MATERIAL_NUMBERRequest request) {
            return base.Channel.MATERIAL_NUMBER(request);
        }
        
        public BLLTests.MM73_ServiceReference.MM73_OUTBOUND_MATERIAL_NUMBERResponse MATERIAL_NUMBER(BLLTests.MM73_ServiceReference.MM73_OUTBOUND_MATERIAL_NUMBER MM73_OUTBOUND_MATERIAL_NUMBER) {
            BLLTests.MM73_ServiceReference.MATERIAL_NUMBERRequest inValue = new BLLTests.MM73_ServiceReference.MATERIAL_NUMBERRequest();
            inValue.MM73_OUTBOUND_MATERIAL_NUMBER = MM73_OUTBOUND_MATERIAL_NUMBER;
            BLLTests.MM73_ServiceReference.MATERIAL_NUMBERResponse retVal = ((BLLTests.MM73_ServiceReference.MM73)(this)).MATERIAL_NUMBER(inValue);
            return retVal.MM73_OUTBOUND_MATERIAL_NUMBERResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BLLTests.MM73_ServiceReference.MATERIAL_NUMBERResponse> BLLTests.MM73_ServiceReference.MM73.MATERIAL_NUMBERAsync(BLLTests.MM73_ServiceReference.MATERIAL_NUMBERRequest request) {
            return base.Channel.MATERIAL_NUMBERAsync(request);
        }
        
        public System.Threading.Tasks.Task<BLLTests.MM73_ServiceReference.MATERIAL_NUMBERResponse> MATERIAL_NUMBERAsync(BLLTests.MM73_ServiceReference.MM73_OUTBOUND_MATERIAL_NUMBER MM73_OUTBOUND_MATERIAL_NUMBER) {
            BLLTests.MM73_ServiceReference.MATERIAL_NUMBERRequest inValue = new BLLTests.MM73_ServiceReference.MATERIAL_NUMBERRequest();
            inValue.MM73_OUTBOUND_MATERIAL_NUMBER = MM73_OUTBOUND_MATERIAL_NUMBER;
            return ((BLLTests.MM73_ServiceReference.MM73)(this)).MATERIAL_NUMBERAsync(inValue);
        }
    }
}
