//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.BizMM65Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BizMM65Service.MM65")]
    public interface MM65 {
        
        // CODEGEN: Generating message contract since the operation inputArtworkNumber is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="inputArtworkNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BLL.BizMM65Service.inputArtworkNumberResponse1 inputArtworkNumber(BLL.BizMM65Service.inputArtworkNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="inputArtworkNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<BLL.BizMM65Service.inputArtworkNumberResponse1> inputArtworkNumberAsync(BLL.BizMM65Service.inputArtworkNumberRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class inputArtworkNumber : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ArtworkObject _artworkObjectField;
        
        private InboundArtwork[] _itemsArtworkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ArtworkObject _artworkObject {
            get {
                return this._artworkObjectField;
            }
            set {
                this._artworkObjectField = value;
                this.RaisePropertyChanged("_artworkObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public InboundArtwork[] _itemsArtwork {
            get {
                return this._itemsArtworkField;
            }
            set {
                this._itemsArtworkField = value;
                this.RaisePropertyChanged("_itemsArtwork");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ArtworkObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string artworkNumberField;
        
        private string dateField;
        
        private string timeField;
        
        private string recordTypeField;
        
        private string materialNumberField;
        
        private string materialDescriptionField;
        
        private string materialCreatedDateField;
        
        private string artworkURLField;
        
        private string statusField;
        
        private string pAUserNameField;
        
        private string pGUserNameField;
        
        private string referenceMaterialField;
        
        private string plantField;
        
        private string printingStyleofPrimaryField;
        
        private string printingStyleofSecondaryField;
        
        private string customersDesignField;
        
        private string customersDesignDetailField;
        
        private string customersSpecField;
        
        private string customersSpecDetailField;
        
        private string customersSizeField;
        
        private string customersSizeDetailField;
        
        private string customerNominatesVendorField;
        
        private string customerNominatesVendorDetailField;
        
        private string customerNominatesColorPantoneField;
        
        private string customerNominatesColorPantoneDetailField;
        
        private string customersBarcodeScanableField;
        
        private string customersBarcodeScanableDetailField;
        
        private string customersBarcodeSpecField;
        
        private string customersBarcodeSpecDetailField;
        
        private string firstInfoGroupField;
        
        private string sONumberField;
        
        private string sOitemField;
        
        private string sOPlantField;
        
        private string pICMKTField;
        
        private string destinationField;
        
        private string remarkNoteofPAField;
        
        private string finalInfoGroupField;
        
        private string remarkNoteofPGField;
        
        private string completeInfoGroupField;
        
        private string productionExpirydatesystemField;
        
        private string seriousnessofcolorprintingField;
        
        private string custIngreNutritionAnalysisField;
        
        private string shadeLimitField;
        
        private string packageQuantityField;
        
        private string wastePercentField;
        
        private string SustainMaterialField;
        private string SustainPlasticField;
        private string SustainReuseableField;
        private string SustainRecyclableField;
        private string SustainComposatableField;
        private string SustainCertificationField;
        private string SustainCertSourcingField;

        private string SustainOtherField;
        private string SusSecondaryPKGWeightField;
        private string SusRecycledContentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ArtworkNumber {
            get {
                return this.artworkNumberField;
            }
            set {
                this.artworkNumberField = value;
                this.RaisePropertyChanged("ArtworkNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RecordType {
            get {
                return this.recordTypeField;
            }
            set {
                this.recordTypeField = value;
                this.RaisePropertyChanged("RecordType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MaterialNumber {
            get {
                return this.materialNumberField;
            }
            set {
                this.materialNumberField = value;
                this.RaisePropertyChanged("MaterialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MaterialDescription {
            get {
                return this.materialDescriptionField;
            }
            set {
                this.materialDescriptionField = value;
                this.RaisePropertyChanged("MaterialDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MaterialCreatedDate {
            get {
                return this.materialCreatedDateField;
            }
            set {
                this.materialCreatedDateField = value;
                this.RaisePropertyChanged("MaterialCreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ArtworkURL {
            get {
                return this.artworkURLField;
            }
            set {
                this.artworkURLField = value;
                this.RaisePropertyChanged("ArtworkURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PAUserName {
            get {
                return this.pAUserNameField;
            }
            set {
                this.pAUserNameField = value;
                this.RaisePropertyChanged("PAUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PGUserName {
            get {
                return this.pGUserNameField;
            }
            set {
                this.pGUserNameField = value;
                this.RaisePropertyChanged("PGUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ReferenceMaterial {
            get {
                return this.referenceMaterialField;
            }
            set {
                this.referenceMaterialField = value;
                this.RaisePropertyChanged("ReferenceMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
                this.RaisePropertyChanged("Plant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PrintingStyleofPrimary {
            get {
                return this.printingStyleofPrimaryField;
            }
            set {
                this.printingStyleofPrimaryField = value;
                this.RaisePropertyChanged("PrintingStyleofPrimary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PrintingStyleofSecondary {
            get {
                return this.printingStyleofSecondaryField;
            }
            set {
                this.printingStyleofSecondaryField = value;
                this.RaisePropertyChanged("PrintingStyleofSecondary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CustomersDesign {
            get {
                return this.customersDesignField;
            }
            set {
                this.customersDesignField = value;
                this.RaisePropertyChanged("CustomersDesign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CustomersDesignDetail {
            get {
                return this.customersDesignDetailField;
            }
            set {
                this.customersDesignDetailField = value;
                this.RaisePropertyChanged("CustomersDesignDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string CustomersSpec {
            get {
                return this.customersSpecField;
            }
            set {
                this.customersSpecField = value;
                this.RaisePropertyChanged("CustomersSpec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string CustomersSpecDetail {
            get {
                return this.customersSpecDetailField;
            }
            set {
                this.customersSpecDetailField = value;
                this.RaisePropertyChanged("CustomersSpecDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string CustomersSize {
            get {
                return this.customersSizeField;
            }
            set {
                this.customersSizeField = value;
                this.RaisePropertyChanged("CustomersSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string CustomersSizeDetail {
            get {
                return this.customersSizeDetailField;
            }
            set {
                this.customersSizeDetailField = value;
                this.RaisePropertyChanged("CustomersSizeDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string CustomerNominatesVendor {
            get {
                return this.customerNominatesVendorField;
            }
            set {
                this.customerNominatesVendorField = value;
                this.RaisePropertyChanged("CustomerNominatesVendor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string CustomerNominatesVendorDetail {
            get {
                return this.customerNominatesVendorDetailField;
            }
            set {
                this.customerNominatesVendorDetailField = value;
                this.RaisePropertyChanged("CustomerNominatesVendorDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string CustomerNominatesColorPantone {
            get {
                return this.customerNominatesColorPantoneField;
            }
            set {
                this.customerNominatesColorPantoneField = value;
                this.RaisePropertyChanged("CustomerNominatesColorPantone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string CustomerNominatesColorPantoneDetail {
            get {
                return this.customerNominatesColorPantoneDetailField;
            }
            set {
                this.customerNominatesColorPantoneDetailField = value;
                this.RaisePropertyChanged("CustomerNominatesColorPantoneDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string CustomersBarcodeScanable {
            get {
                return this.customersBarcodeScanableField;
            }
            set {
                this.customersBarcodeScanableField = value;
                this.RaisePropertyChanged("CustomersBarcodeScanable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string CustomersBarcodeScanableDetail {
            get {
                return this.customersBarcodeScanableDetailField;
            }
            set {
                this.customersBarcodeScanableDetailField = value;
                this.RaisePropertyChanged("CustomersBarcodeScanableDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string CustomersBarcodeSpec {
            get {
                return this.customersBarcodeSpecField;
            }
            set {
                this.customersBarcodeSpecField = value;
                this.RaisePropertyChanged("CustomersBarcodeSpec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string CustomersBarcodeSpecDetail {
            get {
                return this.customersBarcodeSpecDetailField;
            }
            set {
                this.customersBarcodeSpecDetailField = value;
                this.RaisePropertyChanged("CustomersBarcodeSpecDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string FirstInfoGroup {
            get {
                return this.firstInfoGroupField;
            }
            set {
                this.firstInfoGroupField = value;
                this.RaisePropertyChanged("FirstInfoGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string SONumber {
            get {
                return this.sONumberField;
            }
            set {
                this.sONumberField = value;
                this.RaisePropertyChanged("SONumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string SOitem {
            get {
                return this.sOitemField;
            }
            set {
                this.sOitemField = value;
                this.RaisePropertyChanged("SOitem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string SOPlant {
            get {
                return this.sOPlantField;
            }
            set {
                this.sOPlantField = value;
                this.RaisePropertyChanged("SOPlant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string PICMKT {
            get {
                return this.pICMKTField;
            }
            set {
                this.pICMKTField = value;
                this.RaisePropertyChanged("PICMKT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("Destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string RemarkNoteofPA {
            get {
                return this.remarkNoteofPAField;
            }
            set {
                this.remarkNoteofPAField = value;
                this.RaisePropertyChanged("RemarkNoteofPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string FinalInfoGroup {
            get {
                return this.finalInfoGroupField;
            }
            set {
                this.finalInfoGroupField = value;
                this.RaisePropertyChanged("FinalInfoGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string RemarkNoteofPG {
            get {
                return this.remarkNoteofPGField;
            }
            set {
                this.remarkNoteofPGField = value;
                this.RaisePropertyChanged("RemarkNoteofPG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string CompleteInfoGroup {
            get {
                return this.completeInfoGroupField;
            }
            set {
                this.completeInfoGroupField = value;
                this.RaisePropertyChanged("CompleteInfoGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string ProductionExpirydatesystem {
            get {
                return this.productionExpirydatesystemField;
            }
            set {
                this.productionExpirydatesystemField = value;
                this.RaisePropertyChanged("ProductionExpirydatesystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string Seriousnessofcolorprinting {
            get {
                return this.seriousnessofcolorprintingField;
            }
            set {
                this.seriousnessofcolorprintingField = value;
                this.RaisePropertyChanged("Seriousnessofcolorprinting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string CustIngreNutritionAnalysis {
            get {
                return this.custIngreNutritionAnalysisField;
            }
            set {
                this.custIngreNutritionAnalysisField = value;
                this.RaisePropertyChanged("CustIngreNutritionAnalysis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string ShadeLimit {
            get {
                return this.shadeLimitField;
            }
            set {
                this.shadeLimitField = value;
                this.RaisePropertyChanged("ShadeLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string PackageQuantity {
            get {
                return this.packageQuantityField;
            }
            set {
                this.packageQuantityField = value;
                this.RaisePropertyChanged("PackageQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string WastePercent {
            get {
                return this.wastePercentField;
            }
            set {
                this.wastePercentField = value;
                this.RaisePropertyChanged("WastePercent");
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 45)]
        public string SustainMaterial
        {
            get
            {
                return this.SustainMaterialField;
            }
            set
            {
                this.SustainMaterialField = value;
                this.RaisePropertyChanged("SustainMaterial");
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 46)]
        public string SustainPlastic
        {
            get
            {
                return this.SustainPlasticField;
            }
            set
            {
                this.SustainPlasticField = value;
                this.RaisePropertyChanged("SustainPlastic");
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Order = 47)]
        public string SustainReuseable
        {
            get
            {
                return this.SustainReuseableField;
            }
            set
            {
                this.SustainReuseableField = value;
                this.RaisePropertyChanged("SustainReuseable");
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Order = 48)]
        public string SustainRecyclable
        {
            get
            {
                return this.SustainRecyclableField;
            }
            set
            {
                this.SustainRecyclableField = value;
                this.RaisePropertyChanged("SustainRecyclable");
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 49)]
        public string SustainComposatable
        {
            get
            {
                return this.SustainComposatableField;
            }
            set
            {
                this.SustainComposatableField = value;
                this.RaisePropertyChanged("SustainComposatable");
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 50)]
        public string SustainCertification
        {
            get
            {
                return this.SustainCertificationField;
            }
            set
            {
                this.SustainCertificationField = value;
                this.RaisePropertyChanged("SustainCertification");
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Order = 51)]
        public string SustainCertSourcing
        {
            get
            {
                return this.SustainCertSourcingField;
            }
            set
            {
                this.SustainCertSourcingField = value;
                this.RaisePropertyChanged("SustainCertSourcing");
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 52)]
        public string SustainOther
        {
            get
            {
                return this.SustainOtherField;
            }
            set
            {
                this.SustainOtherField = value;
                this.RaisePropertyChanged("SustainOther");
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 53)]
        public string SusSecondaryPKGWeight
        {
            get
            {
                return this.SusSecondaryPKGWeightField;
            }
            set
            {
                this.SusSecondaryPKGWeightField = value;
                this.RaisePropertyChanged("SusSecondaryPKGWeight");
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Order = 54)]
        public string SusRecycledContent
        {
            get
            {
                return this.SusRecycledContentField;
            }
            set
            {
                this.SusRecycledContentField = value;
                this.RaisePropertyChanged("SusRecycledContent");
            }
        }
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InboundArtwork : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string artworkNumberField;
        
        private string dateField;
        
        private string timeField;
        
        private string characteristicField;
        
        private string valueField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ArtworkNumber {
            get {
                return this.artworkNumberField;
            }
            set {
                this.artworkNumberField = value;
                this.RaisePropertyChanged("ArtworkNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Characteristic {
            get {
                return this.characteristicField;
            }
            set {
                this.characteristicField = value;
                this.RaisePropertyChanged("Characteristic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class inputArtworkNumberResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string inputArtworkNumberResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string inputArtworkNumberResult {
            get {
                return this.inputArtworkNumberResultField;
            }
            set {
                this.inputArtworkNumberResultField = value;
                this.RaisePropertyChanged("inputArtworkNumberResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputArtworkNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BLL.BizMM65Service.inputArtworkNumber inputArtworkNumber;
        
        public inputArtworkNumberRequest() {
        }
        
        public inputArtworkNumberRequest(BLL.BizMM65Service.inputArtworkNumber inputArtworkNumber) {
            this.inputArtworkNumber = inputArtworkNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inputArtworkNumberResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BLL.BizMM65Service.inputArtworkNumberResponse inputArtworkNumberResponse;
        
        public inputArtworkNumberResponse1() {
        }
        
        public inputArtworkNumberResponse1(BLL.BizMM65Service.inputArtworkNumberResponse inputArtworkNumberResponse) {
            this.inputArtworkNumberResponse = inputArtworkNumberResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MM65Channel : BLL.BizMM65Service.MM65, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MM65Client : System.ServiceModel.ClientBase<BLL.BizMM65Service.MM65>, BLL.BizMM65Service.MM65 {
        
        public MM65Client() {
        }
        
        public MM65Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MM65Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MM65Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MM65Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.BizMM65Service.inputArtworkNumberResponse1 BLL.BizMM65Service.MM65.inputArtworkNumber(BLL.BizMM65Service.inputArtworkNumberRequest request) {
            return base.Channel.inputArtworkNumber(request);
        }
        
        public BLL.BizMM65Service.inputArtworkNumberResponse inputArtworkNumber(BLL.BizMM65Service.inputArtworkNumber inputArtworkNumber1) {
            BLL.BizMM65Service.inputArtworkNumberRequest inValue = new BLL.BizMM65Service.inputArtworkNumberRequest();
            inValue.inputArtworkNumber = inputArtworkNumber1;
            BLL.BizMM65Service.inputArtworkNumberResponse1 retVal = ((BLL.BizMM65Service.MM65)(this)).inputArtworkNumber(inValue);
            return retVal.inputArtworkNumberResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BLL.BizMM65Service.inputArtworkNumberResponse1> BLL.BizMM65Service.MM65.inputArtworkNumberAsync(BLL.BizMM65Service.inputArtworkNumberRequest request) {
            return base.Channel.inputArtworkNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<BLL.BizMM65Service.inputArtworkNumberResponse1> inputArtworkNumberAsync(BLL.BizMM65Service.inputArtworkNumber inputArtworkNumber) {
            BLL.BizMM65Service.inputArtworkNumberRequest inValue = new BLL.BizMM65Service.inputArtworkNumberRequest();
            inValue.inputArtworkNumber = inputArtworkNumber;
            return ((BLL.BizMM65Service.MM65)(this)).inputArtworkNumberAsync(inValue);
        }
    }
}
